name: Contract CI
on:
  [push]
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize

jobs:
  contract-coverage:
    runs-on: ubuntu-latest
    container:
      image: trailofbits/etheno:latest
      options: --user root
    steps:
      - name: ğŸ— Checkout Repo
        uses: actions/checkout@v2
        with:
          cache: yarn

      - name: Install Git
        run: apk add --no-cache git openssh

      - name: Turborepo Prune
        run: npx turbo prune --scope=contracts

      - name: Install dependencies
        run: |
          cd out
          yarn install --prefer-offline --frozen-lockfile

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ§¶ Install Packages with Yarn
        run: yarn install

      - name: âš™ï¸ Compile Contracts
        run: cd ./packages/contracts && yarn hardhat compile

      - name: ğŸ§ª Run Coverage
        run: cd ./packages/contracts && yarn hardhat coverage

      - name: ğŸ§ª Run Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: .packages/contracts/coverage/lcov.info
