name: Contract Coverage
on:
  [push]
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize

jobs:
  contract-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout Repo
        uses: actions/checkout@v2
        cache: yarn

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ§¶ Install Packages with Yarn
        run: yarn install

      - name: ğŸ§ª Run Coverage
        run: yarn hardhat coverage

      - name: ğŸ§ª Run Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: .packages/contracts/coverage/lcov.info
